[package]
name = "auto_pgpalt"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
opt-level = "z"
lto = true
# was seething because my binary was bigger than go

[dependencies]
cli-clipboard = "0.4.0"
pgp = "0.15.0"
regex = "1.11.1"
